# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        active: prod
    datasource:
        url: jdbc:mysql://localhost:3306/<%= nameCases.kebab %>?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver

server:
    port: 8080

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the DuikerProperties above
# ===================================================================

application:
