# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    sleuth:
        # Percentage of requests that should be sampled. E.g. 1.0 - 100% requests should be
        # sampled. The precision is whole-numbers only (i.e. there's no support for 0.1% of
        # the traces).
        sampler.percentage: 0.1
        # Enable support for RxJava via RxJavaSchedulersHook.
        rxjava.schedulers.hook.enabled: false
    zipkin:
        # URL of the zipkin query server instance. You can also provide
        # the service id of the Zipkin server if Zipkin's registered in
        # service discovery (e.g. http://zipkinserver/)
        baseUrl: http://zipkin/
        # Enabling of locating the host name via service discovery
        locator.discovery.enabled: true

# 元数据 Map
eureka.instance.metadata-map:
    # 管理端口号，服务治理用
    management.port: ${management.port}
    # 集群名称
    cluster: ${spring.application.name}
    # 部署颜色，蓝绿发布，读取环境变量 deploycolor
    deploycolor: ${deploycolor:}

security:
    basic:
        # Enable basic authentication.
        enabled: false

# 管理端口号，服务治理用
management:
    port: <%= Number(port) + 1000 %>
    security.enabled: false

# 开启 feign 熔断功能
feign.hystrix.enabled: true

info:
    project:
        version: 0.0.1-SNAPSHOT
        title: <%= name %>
        description:

mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml
    global-config:
        # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: 0
        # 驼峰下划线转换
        db-column-underline: true
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false

duiker:
    swagger.scan-base-package: <%= groupCases.splitByDot %>.<%= nameCases.splitByDot %>.web.rest

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
# ===================================================================

application:
