spring:
    zipkin:
        baseUrl: http://zipkin/
        locator.discovery.enabled: true
    liquibase:
        change-log: 'classpath:/liquibase/master.xml'

spring.sleuth.rxjava.schedulers.hook.enabled: false

eureka.instance.metadataMap.cluster: ${name:message}

info:
    project:
        version: 0.0.1-SNAPSHOT
        title: message
        description: message service

mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml
    global-config:
        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: 0
        #驼峰下划线转换
        db-column-underline: true
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
# ===================================================================
application: